/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookRouteImport } from './routes/book'
import { Route as CopyRouteImport } from './routes/copy'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as LabRouteImport } from './routes/lab'
import { Route as TapeRouteImport } from './routes/tape'
import { Route as ApiHoldersRouteImport } from './routes/api/holders'
import { Route as ApiPulseRouteImport } from './routes/api/pulse'
import { Route as ApiQuoteRouteImport } from './routes/api/quote'
import { Route as ApiSendRouteImport } from './routes/api/send'
import { Route as ApiSolRouteImport } from './routes/api/sol'
import { Route as ApiSwapRouteImport } from './routes/api/swap'
import { Route as ApiTxRouteImport } from './routes/api/tx'
import { Route as TokenIdRouteImport } from './routes/token.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const CopyRoute = CopyRouteImport.update({
  id: '/copy',
  path: '/copy',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const TapeRoute = TapeRouteImport.update({
  id: '/tape',
  path: '/tape',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHoldersRoute = ApiHoldersRouteImport.update({
  id: '/api/holders',
  path: '/api/holders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPulseRoute = ApiPulseRouteImport.update({
  id: '/api/pulse',
  path: '/api/pulse',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuoteRoute = ApiQuoteRouteImport.update({
  id: '/api/quote',
  path: '/api/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSendRoute = ApiSendRouteImport.update({
  id: '/api/send',
  path: '/api/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSolRoute = ApiSolRouteImport.update({
  id: '/api/sol',
  path: '/api/sol',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSwapRoute = ApiSwapRouteImport.update({
  id: '/api/swap',
  path: '/api/swap',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTxRoute = ApiTxRouteImport.update({
  id: '/api/tx',
  path: '/api/tx',
  getParentRoute: () => rootRouteImport,
} as any)
const TokenIdRoute = TokenIdRouteImport.update({
  id: '/token/$id',
  path: '/token/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/copy': typeof CopyRoute
  '/discover': typeof DiscoverRoute
  '/lab': typeof LabRoute
  '/tape': typeof TapeRoute
  '/api/holders': typeof ApiHoldersRoute
  '/api/pulse': typeof ApiPulseRoute
  '/api/quote': typeof ApiQuoteRoute
  '/api/send': typeof ApiSendRoute
  '/api/sol': typeof ApiSolRoute
  '/api/swap': typeof ApiSwapRoute
  '/api/tx': typeof ApiTxRoute
  '/token/$id': typeof TokenIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/copy': typeof CopyRoute
  '/discover': typeof DiscoverRoute
  '/lab': typeof LabRoute
  '/tape': typeof TapeRoute
  '/api/holders': typeof ApiHoldersRoute
  '/api/pulse': typeof ApiPulseRoute
  '/api/quote': typeof ApiQuoteRoute
  '/api/send': typeof ApiSendRoute
  '/api/sol': typeof ApiSolRoute
  '/api/swap': typeof ApiSwapRoute
  '/api/tx': typeof ApiTxRoute
  '/token/$id': typeof TokenIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/copy': typeof CopyRoute
  '/discover': typeof DiscoverRoute
  '/lab': typeof LabRoute
  '/tape': typeof TapeRoute
  '/api/holders': typeof ApiHoldersRoute
  '/api/pulse': typeof ApiPulseRoute
  '/api/quote': typeof ApiQuoteRoute
  '/api/send': typeof ApiSendRoute
  '/api/sol': typeof ApiSolRoute
  '/api/swap': typeof ApiSwapRoute
  '/api/tx': typeof ApiTxRoute
  '/token/$id': typeof TokenIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/book'
    | '/copy'
    | '/discover'
    | '/lab'
    | '/tape'
    | '/api/holders'
    | '/api/pulse'
    | '/api/quote'
    | '/api/send'
    | '/api/sol'
    | '/api/swap'
    | '/api/tx'
    | '/token/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/book'
    | '/copy'
    | '/discover'
    | '/lab'
    | '/tape'
    | '/api/holders'
    | '/api/pulse'
    | '/api/quote'
    | '/api/send'
    | '/api/sol'
    | '/api/swap'
    | '/api/tx'
    | '/token/$id'
  id:
    | '__root__'
    | '/'
    | '/book'
    | '/copy'
    | '/discover'
    | '/lab'
    | '/tape'
    | '/api/holders'
    | '/api/pulse'
    | '/api/quote'
    | '/api/send'
    | '/api/sol'
    | '/api/swap'
    | '/api/tx'
    | '/token/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookRoute: typeof BookRoute
  CopyRoute: typeof CopyRoute
  DiscoverRoute: typeof DiscoverRoute
  LabRoute: typeof LabRoute
  TapeRoute: typeof TapeRoute
  ApiHoldersRoute: typeof ApiHoldersRoute
  ApiPulseRoute: typeof ApiPulseRoute
  ApiQuoteRoute: typeof ApiQuoteRoute
  ApiSendRoute: typeof ApiSendRoute
  ApiSolRoute: typeof ApiSolRoute
  ApiSwapRoute: typeof ApiSwapRoute
  ApiTxRoute: typeof ApiTxRoute
  TokenIdRoute: typeof TokenIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copy': {
      id: '/copy'
      path: '/copy'
      fullPath: '/copy'
      preLoaderRoute: typeof CopyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tape': {
      id: '/tape'
      path: '/tape'
      fullPath: '/tape'
      preLoaderRoute: typeof TapeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/holders': {
      id: '/api/holders'
      path: '/api/holders'
      fullPath: '/api/holders'
      preLoaderRoute: typeof ApiHoldersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pulse': {
      id: '/api/pulse'
      path: '/api/pulse'
      fullPath: '/api/pulse'
      preLoaderRoute: typeof ApiPulseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quote': {
      id: '/api/quote'
      path: '/api/quote'
      fullPath: '/api/quote'
      preLoaderRoute: typeof ApiQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send': {
      id: '/api/send'
      path: '/api/send'
      fullPath: '/api/send'
      preLoaderRoute: typeof ApiSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sol': {
      id: '/api/sol'
      path: '/api/sol'
      fullPath: '/api/sol'
      preLoaderRoute: typeof ApiSolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/swap': {
      id: '/api/swap'
      path: '/api/swap'
      fullPath: '/api/swap'
      preLoaderRoute: typeof ApiSwapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tx': {
      id: '/api/tx'
      path: '/api/tx'
      fullPath: '/api/tx'
      preLoaderRoute: typeof ApiTxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/token/$id': {
      id: '/token/$id'
      path: '/token/$id'
      fullPath: '/token/$id'
      preLoaderRoute: typeof TokenIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookRoute: BookRoute,
  CopyRoute: CopyRoute,
  DiscoverRoute: DiscoverRoute,
  LabRoute: LabRoute,
  TapeRoute: TapeRoute,
  ApiHoldersRoute: ApiHoldersRoute,
  ApiPulseRoute: ApiPulseRoute,
  ApiQuoteRoute: ApiQuoteRoute,
  ApiSendRoute: ApiSendRoute,
  ApiSolRoute: ApiSolRoute,
  ApiSwapRoute: ApiSwapRoute,
  ApiTxRoute: ApiTxRoute,
  TokenIdRoute: TokenIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
